#!/usr/bin/env bash

set -e

ORG_PATH="github.com/coreos"
REPO_PATH="${ORG_PATH}/coreos-userdata-validator"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export CGO_ENABLED=0

go build -o bin/validate ${REPO_PATH}
